
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
dotenv: .env
networks:
  default: development
  kovan: active
wallets:
  from_key: ${PRIVATE_KEY}